// Code generated by protoc-gen-easymicro-client. DO NOT EDIT.
package idgen

import (
	"sync"

	easymicrogrpc "github.com/995933447/easymicro/grpc"
	"context"
	"google.golang.org/grpc"
)

const (
	EasymicroGRPCSchema    = "idgen"
	EasymicroDiscoveryName = "idgen"
)

const EasymicroGRPCPbServiceNameIdGen = "idgen.IdGen"

var IdGenDefault = &IdGen{}

func IdGenGRPC() *IdGen {
	return IdGenDefault
}

func NewIdGenGRPC(dialOpts ...grpc.DialOption) *IdGen {
	return &IdGen{
		dialOpts: dialOpts,
	}
}

type IdGen struct {
	c        IdGenClient
	conn     *grpc.ClientConn
	once     sync.Once
	mu       sync.RWMutex
	dialOpts []grpc.DialOption
}

func (s *IdGen) Close() error {
	err := s.conn.Close()
	if err != nil {
		return err
	}
	return nil
}

func (s *IdGen) prepareConn() error {
	var err error
	s.once.Do(func() {
		var conn *grpc.ClientConn
		opts := s.dialOpts
		if opts == nil {
			opts = easymicrogrpc.BuildServiceDialOpts(EasymicroGRPCPbServiceNameIdGen)
		}
		conn, err = grpc.NewClient(EasymicroGRPCSchema+":///"+EasymicroGRPCPbServiceNameIdGen, opts...)
		if err != nil {
			return
		}
		s.conn = conn
		s.c = NewIdGenClient(conn)
	})
	if err != nil {
		return err
	}
	return nil
}

func (s *IdGen) AllocId(ctx context.Context, in *AllocIdReq, opts ...grpc.CallOption) (*AllocIdResp, error) {
	if err := s.prepareConn(); err != nil {
		return nil, err
	}

	return s.c.AllocId(ctx, in, opts...)
}

func (s *IdGen) MAllocId(ctx context.Context, in *MAllocIdReq, opts ...grpc.CallOption) (*MAllocIdResp, error) {
	if err := s.prepareConn(); err != nil {
		return nil, err
	}

	return s.c.MAllocId(ctx, in, opts...)
}
