// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v4.24.2
// source: idgen.proto

package idgen

import (
	_ "github.com/995933447/easymicro/pb"
	_ "github.com/995933447/mgorm/pb"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AllocIdReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TbName        string                 `protobuf:"bytes,1,opt,name=tb_name,json=tbName,proto3" json:"tb_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AllocIdReq) Reset() {
	*x = AllocIdReq{}
	mi := &file_idgen_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AllocIdReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllocIdReq) ProtoMessage() {}

func (x *AllocIdReq) ProtoReflect() protoreflect.Message {
	mi := &file_idgen_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllocIdReq.ProtoReflect.Descriptor instead.
func (*AllocIdReq) Descriptor() ([]byte, []int) {
	return file_idgen_proto_rawDescGZIP(), []int{0}
}

func (x *AllocIdReq) GetTbName() string {
	if x != nil {
		return x.TbName
	}
	return ""
}

type AllocIdResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AllocIdResp) Reset() {
	*x = AllocIdResp{}
	mi := &file_idgen_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AllocIdResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllocIdResp) ProtoMessage() {}

func (x *AllocIdResp) ProtoReflect() protoreflect.Message {
	mi := &file_idgen_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllocIdResp.ProtoReflect.Descriptor instead.
func (*AllocIdResp) Descriptor() ([]byte, []int) {
	return file_idgen_proto_rawDescGZIP(), []int{1}
}

func (x *AllocIdResp) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type MAllocIdReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TbName        string                 `protobuf:"bytes,1,opt,name=tb_name,json=tbName,proto3" json:"tb_name,omitempty"`
	Count         int32                  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MAllocIdReq) Reset() {
	*x = MAllocIdReq{}
	mi := &file_idgen_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MAllocIdReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MAllocIdReq) ProtoMessage() {}

func (x *MAllocIdReq) ProtoReflect() protoreflect.Message {
	mi := &file_idgen_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MAllocIdReq.ProtoReflect.Descriptor instead.
func (*MAllocIdReq) Descriptor() ([]byte, []int) {
	return file_idgen_proto_rawDescGZIP(), []int{2}
}

func (x *MAllocIdReq) GetTbName() string {
	if x != nil {
		return x.TbName
	}
	return ""
}

func (x *MAllocIdReq) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

type MAllocIdResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          []uint64               `protobuf:"varint,1,rep,packed,name=list,proto3" json:"list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MAllocIdResp) Reset() {
	*x = MAllocIdResp{}
	mi := &file_idgen_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MAllocIdResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MAllocIdResp) ProtoMessage() {}

func (x *MAllocIdResp) ProtoReflect() protoreflect.Message {
	mi := &file_idgen_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MAllocIdResp.ProtoReflect.Descriptor instead.
func (*MAllocIdResp) Descriptor() ([]byte, []int) {
	return file_idgen_proto_rawDescGZIP(), []int{3}
}

func (x *MAllocIdResp) GetList() []uint64 {
	if x != nil {
		return x.List
	}
	return nil
}

type IdSegment struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TbName        string                 `protobuf:"bytes,5,opt,name=tb_name,json=tbName,proto3" json:"tb_name,omitempty"`
	MaxId         uint64                 `protobuf:"varint,6,opt,name=max_id,json=maxId,proto3" json:"max_id,omitempty"`
	Step          uint64                 `protobuf:"varint,7,opt,name=step,proto3" json:"step,omitempty"`
	Remark        string                 `protobuf:"bytes,8,opt,name=remark,proto3" json:"remark,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IdSegment) Reset() {
	*x = IdSegment{}
	mi := &file_idgen_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IdSegment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IdSegment) ProtoMessage() {}

func (x *IdSegment) ProtoReflect() protoreflect.Message {
	mi := &file_idgen_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IdSegment.ProtoReflect.Descriptor instead.
func (*IdSegment) Descriptor() ([]byte, []int) {
	return file_idgen_proto_rawDescGZIP(), []int{4}
}

func (x *IdSegment) GetTbName() string {
	if x != nil {
		return x.TbName
	}
	return ""
}

func (x *IdSegment) GetMaxId() uint64 {
	if x != nil {
		return x.MaxId
	}
	return 0
}

func (x *IdSegment) GetStep() uint64 {
	if x != nil {
		return x.Step
	}
	return 0
}

func (x *IdSegment) GetRemark() string {
	if x != nil {
		return x.Remark
	}
	return ""
}

var File_idgen_proto protoreflect.FileDescriptor

const file_idgen_proto_rawDesc = "" +
	"\n" +
	"\vidgen.proto\x12\x05idgen\x1a\x0fmgorm_ext.proto\x1a\x13easymicro_ext.proto\"%\n" +
	"\n" +
	"AllocIdReq\x12\x17\n" +
	"\atb_name\x18\x01 \x01(\tR\x06tbName\"\x1d\n" +
	"\vAllocIdResp\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\"<\n" +
	"\vMAllocIdReq\x12\x17\n" +
	"\atb_name\x18\x01 \x01(\tR\x06tbName\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x05R\x05count\"\"\n" +
	"\fMAllocIdResp\x12\x12\n" +
	"\x04list\x18\x01 \x03(\x04R\x04list\"\x90\x01\n" +
	"\tIdSegment\x12\x17\n" +
	"\atb_name\x18\x05 \x01(\tR\x06tbName\x12\x15\n" +
	"\x06max_id\x18\x06 \x01(\x04R\x05maxId\x12\x12\n" +
	"\x04step\x18\a \x01(\x04R\x04step\x12\x16\n" +
	"\x06remark\x18\b \x01(\tR\x06remark:'\x8a\x8e%#\n" +
	"\x05idgen\x12\x05idgen\x1a\n" +
	"id_segment:\atb_name2n\n" +
	"\x05IdGen\x120\n" +
	"\aAllocId\x12\x11.idgen.AllocIdReq\x1a\x12.idgen.AllocIdResp\x123\n" +
	"\bMAllocId\x12\x12.idgen.MAllocIdReq\x1a\x13.idgen.MAllocIdRespB:\x8a\x9d \x14 \x018\x01@\x01Z\x05idgenb\x05idgenZ github.com/995933447/idgen/idgenb\x06proto3"

var (
	file_idgen_proto_rawDescOnce sync.Once
	file_idgen_proto_rawDescData []byte
)

func file_idgen_proto_rawDescGZIP() []byte {
	file_idgen_proto_rawDescOnce.Do(func() {
		file_idgen_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_idgen_proto_rawDesc), len(file_idgen_proto_rawDesc)))
	})
	return file_idgen_proto_rawDescData
}

var file_idgen_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_idgen_proto_goTypes = []any{
	(*AllocIdReq)(nil),   // 0: idgen.AllocIdReq
	(*AllocIdResp)(nil),  // 1: idgen.AllocIdResp
	(*MAllocIdReq)(nil),  // 2: idgen.MAllocIdReq
	(*MAllocIdResp)(nil), // 3: idgen.MAllocIdResp
	(*IdSegment)(nil),    // 4: idgen.IdSegment
}
var file_idgen_proto_depIdxs = []int32{
	0, // 0: idgen.IdGen.AllocId:input_type -> idgen.AllocIdReq
	2, // 1: idgen.IdGen.MAllocId:input_type -> idgen.MAllocIdReq
	1, // 2: idgen.IdGen.AllocId:output_type -> idgen.AllocIdResp
	3, // 3: idgen.IdGen.MAllocId:output_type -> idgen.MAllocIdResp
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_idgen_proto_init() }
func file_idgen_proto_init() {
	if File_idgen_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_idgen_proto_rawDesc), len(file_idgen_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_idgen_proto_goTypes,
		DependencyIndexes: file_idgen_proto_depIdxs,
		MessageInfos:      file_idgen_proto_msgTypes,
	}.Build()
	File_idgen_proto = out.File
	file_idgen_proto_goTypes = nil
	file_idgen_proto_depIdxs = nil
}
