// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v4.24.2
// source: idgen.proto

package idgen

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	IdGen_AllocId_FullMethodName  = "/idgen.IdGen/AllocId"
	IdGen_MAllocId_FullMethodName = "/idgen.IdGen/MAllocId"
)

// IdGenClient is the client API for IdGen service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type IdGenClient interface {
	AllocId(ctx context.Context, in *AllocIdReq, opts ...grpc.CallOption) (*AllocIdResp, error)
	MAllocId(ctx context.Context, in *MAllocIdReq, opts ...grpc.CallOption) (*MAllocIdResp, error)
}

type idGenClient struct {
	cc grpc.ClientConnInterface
}

func NewIdGenClient(cc grpc.ClientConnInterface) IdGenClient {
	return &idGenClient{cc}
}

func (c *idGenClient) AllocId(ctx context.Context, in *AllocIdReq, opts ...grpc.CallOption) (*AllocIdResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AllocIdResp)
	err := c.cc.Invoke(ctx, IdGen_AllocId_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *idGenClient) MAllocId(ctx context.Context, in *MAllocIdReq, opts ...grpc.CallOption) (*MAllocIdResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MAllocIdResp)
	err := c.cc.Invoke(ctx, IdGen_MAllocId_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// IdGenServer is the server API for IdGen service.
// All implementations must embed UnimplementedIdGenServer
// for forward compatibility.
type IdGenServer interface {
	AllocId(context.Context, *AllocIdReq) (*AllocIdResp, error)
	MAllocId(context.Context, *MAllocIdReq) (*MAllocIdResp, error)
	mustEmbedUnimplementedIdGenServer()
}

// UnimplementedIdGenServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedIdGenServer struct{}

func (UnimplementedIdGenServer) AllocId(context.Context, *AllocIdReq) (*AllocIdResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AllocId not implemented")
}
func (UnimplementedIdGenServer) MAllocId(context.Context, *MAllocIdReq) (*MAllocIdResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MAllocId not implemented")
}
func (UnimplementedIdGenServer) mustEmbedUnimplementedIdGenServer() {}
func (UnimplementedIdGenServer) testEmbeddedByValue()               {}

// UnsafeIdGenServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to IdGenServer will
// result in compilation errors.
type UnsafeIdGenServer interface {
	mustEmbedUnimplementedIdGenServer()
}

func RegisterIdGenServer(s grpc.ServiceRegistrar, srv IdGenServer) {
	// If the following call pancis, it indicates UnimplementedIdGenServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&IdGen_ServiceDesc, srv)
}

func _IdGen_AllocId_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AllocIdReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdGenServer).AllocId(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IdGen_AllocId_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdGenServer).AllocId(ctx, req.(*AllocIdReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _IdGen_MAllocId_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MAllocIdReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdGenServer).MAllocId(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IdGen_MAllocId_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdGenServer).MAllocId(ctx, req.(*MAllocIdReq))
	}
	return interceptor(ctx, in, info, handler)
}

// IdGen_ServiceDesc is the grpc.ServiceDesc for IdGen service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var IdGen_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "idgen.IdGen",
	HandlerType: (*IdGenServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AllocId",
			Handler:    _IdGen_AllocId_Handler,
		},
		{
			MethodName: "MAllocId",
			Handler:    _IdGen_MAllocId_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "idgen.proto",
}
