// Code generated by protoc-gen-easymicro-server. DO NOT EDIT.
package boot

import (
	"github.com/995933447/easymicro/nats"
	"github.com/995933447/idgen/idgen"
	"github.com/995933447/idgen/idgenserver/handler"

	"github.com/995933447/easymicro/grpc/middleservice/healthreporter"
)

func RegisterNatsRPCRoutes() error {
	var err error

	err = nats.HandleLikeGRPC(idgen.EasymicroGRPCPbServiceNameIdGen, "AllocId", handler.IdGenHandler.AllocId, func() *idgen.AllocIdReq {
		return &idgen.AllocIdReq{}
	})
	if err != nil {
		return err
	}

	err = nats.HandleLikeGRPC(idgen.EasymicroGRPCPbServiceNameIdGen, "MAllocId", handler.IdGenHandler.MAllocId, func() *idgen.MAllocIdReq {
		return &idgen.MAllocIdReq{}
	})
	if err != nil {
		return err
	}

	err = nats.HandleLikeGRPC("healthreporter.HealthReporter", "Ping", healthreporter.NewReporter(ServiceNames).Ping, func() *healthreporter.PingReq {
		return &healthreporter.PingReq{}
	})
	if err != nil {
		return err
	}

	return nil
}
