// Code generated by protoc-gen-easymicro-server. DO NOT EDIT.
package boot

import (
	"github.com/995933447/idgen/idgen"
	"github.com/995933447/idgen/idgenserver/handler"
	"google.golang.org/grpc"
)

var ServiceNames = []string{
	idgen.EasymicroGRPCPbServiceNameIdGen,
}

var RegisterServiceServers = func(server *grpc.Server) error {
	idgen.RegisterIdGenServer(server, handler.IdGenHandler)
	return nil
}
